changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - false-positive
    - title: Rules and language packs
      labels:
        - rules
        - english
        - russian
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
