#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from humanizer_os.registry import RuleRegistry  # noqa: E402


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def build_catalog() -> str:
    registry = RuleRegistry()
    lines = [
        "# Built-in rule catalog",
        "",
        "> Generated by `python scripts/generate_rule_catalog.py`. Do not edit by hand.",
        "",
        (
            "Rules report observable patterns. They do not establish whether a human "
            "or a model wrote a text."
        ),
        "",
    ]
    for locale, label in (("en", "English"), ("ru", "Русский")):
        rules = registry.list(locale)
        categories = Counter(rule.category for rule in rules)
        lines.extend(
            [
                f"## {label}",
                "",
                f"{len(rules)} rules: "
                + ", ".join(f"{key} {value}" for key, value in sorted(categories.items()))
                + ".",
                "",
                "| ID | Category | Severity | Confidence | Rule | Safe fix |",
                "|---|---|---|---|---|---|",
            ]
        )
        for rule in rules:
            lines.append(
                f"| `{rule.id}` | {rule.category} | {rule.severity} | {rule.confidence} | "
                f"{escape(rule.name)} | {'yes' if rule.autofix and rule.autofix.safe else 'no'} |"
            )
        lines.append("")

        lines.extend(
            [
                "> Use `humanizer-os explain RULE_ID` for the full description, review advice, ",
                "> genre limits, protected contexts, and provenance for one rule.",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or verify the built-in rule catalog.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed catalog is stale.",
    )
    args = parser.parse_args()

    output = ROOT / "docs" / "RULE_CATALOG.md"
    generated = build_catalog()
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != generated:
            print(
                "Rule catalog is stale. Run: python scripts/generate_rule_catalog.py",
                file=sys.stderr,
            )
            return 1
        print("Rule catalog is up to date")
        return 0

    output.write_text(generated, encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
